#
# Copyright (C) 2008-2022 fibreyu
#
# This is free software, licensed under the Apache License, Version 2.0 .
#

include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-socat
PKG_VERSION:=1.7.4.1
PKG_RELEASE:=20221015
PKG_MAINTAINER:=fibreyu
LUCI_TITLE:=socat
LUCI_DEPENDS:=+socat
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature