#!/bin/sh

# set timezone and ntp server
uci set system.@system[0].timezone=CST-8
uci set system.@system[0].zonename=Asia/Shanghai
uci add_list system.ntp.server='ntp.aliyun.com'
uci add_list system.ntp.server='time1.cloud.tencent.com'
uci add_list system.ntp.server='time.ustc.edu.cn'
uci add_list system.ntp.server='cn.pool.ntp.org'
uci commit system

# lan ip
lan_ip='10.0.0.88'
gateway='10.0.0.253'
dns_ip=${gateway}

# change password
sed -i 's/root:::0:99999:7:::/root:$1$2Ep0SUcR$A00OPM0TNK6zRWMVP017M0:19282:0:99999:7:::/g' /etc/shadow

# change ip and gate way
sed -i "s/192.168.1.1/${lan_ip}/g" /etc/config/network
sed -i "/option ipaddr '${lan_ip}'/a\\\tlist dns '${dns_ip}'" /etc/config/network
sed -i "/option ipaddr '${lan_ip}'/a\\\toption gateway '${gateway}'" /etc/config/network


# change dhcp
# dns server
sed -i "/config dhcp 'lan'/a\\\tlist dhcp_option '6,${lan_ip}'" /etc/config/dhcp
# gateway
sed -i "/config dhcp 'lan'/a\\\tlist dhcp_option '3,${lan_ip}'" /etc/config/dhcp
# netmask
sed -i "/config dhcp 'lan'/a\\\tlist dhcp_option '1,255.255.255.0'" /etc/config/dhcp
# ip pool size
sed -i "/option limit/d" /etc/config/dhcp
sed -i "/config dhcp 'lan'/a\\\toption limit '200'" /etc/config/dhcp
# start ip pool
sed -i "/option start/d" /etc/config/dhcp
sed -i "/config dhcp 'lan'/a\\\toption start '1'" /etc/config/dhcp


# login ttyd
sed -i 's/login/login -f root/g' /etc/config/ttyd
# fix ttyd not change after lan ip change bug
sed -i 's/${interface:+-i /#${interface:+-i /g' /etc/init.d/ttyd

# vim
# fix E1187: Failed to source defaults.vim bug
echo "set nocompatible" >> ~/.vimrc
echo "set nu" >> ~/.vimrc

# language
sed '/option lang/d' /etc/config/luci
sed "/config core 'main'/a\\\toption lang 'zh_cn'" /etc/config/luci

exit 0